name: Test pipeline

on:
  - push

jobs:
  test:
    name: Unit tests
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4.2.1
      - uses: actions/setup-java@v4.2.1
        with:
          java-version: '22.0.1'
          distribution: 'temurin'
      - run: ./mvnw test
        name: Execute maven test